<?php

namespace App\Filament\Pages\planification;

use App\Models\Ild;
use App\Models\Rld;
use Faker\Provider\Text;
use Filament\Forms\Components\FileUpload;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Actions\Action;
use Filament\Tables\Actions\DeleteAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Grouping\Group;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Spatie\SimpleExcel\SimpleExcelReader;




class ptba extends Page implements HasTable
{

    use InteractsWithTable;

    protected static ?string $navigationLabel = "PTBA Arbitrage";
    protected static ?string $title = "programme de travail et budget annuel";
    protected static ?string $navigationGroup = "Planification";

    protected static string $view = 'filament.pages.planification.ptba';

    protected function getTableQuery(): Builder|Relation|null
    {
        return \App\Models\Ptba::query()->where('status', '=', 10);
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('exporter')
                ->icon('heroicon-s-arrow-down-tray')
                ->label("Exporter")
                ->action(function(){

                }),
        ];
    }

    public function getTableColumns(): array
    {
        return [
            TextColumn::make('departement.nom')->label("Departement"),
            TextColumn::make('updated_at')->label("Date de soumission"),
            TextColumn::make('montantRld')
                ->label('Montant')
                ->money('CFA'),
            TextColumn::make('status')
                ->badge()
                ->color(fn($state)=> STATES_COLORS[$state])
                ->formatStateUsing(fn($state) => STATES_LABEL[$state])
                ->label('Status')
        ];
    }

    public static function getNavigationBadge(): ?string
    {
        return \App\Models\Ptba::query()->where('status', '=', 10)->count(); // TODO: Change the autogenerated stub
    }


    public function getTableActions(): array
    {
        return [
          \Filament\Tables\Actions\Action::make('exporter')->label("Télécharger")
            ->icon('heroicon-o-arrow-down-on-square')
            ->action(function($record){
                return response()
                    ->download($record->file, $record->departement->nom.'_ptba.xlsx');
            }),
            \Filament\Tables\Actions\Action::make('importer')->label("Joindre")
                ->hidden(fn($record) => $record->status > 20)
                ->icon('heroicon-o-arrow-up-on-square')
                    ->form([
                        FileUpload::make('file')->label("PTBA arbitré")
                    ])
                ->action(function($data){
                    $excel = SimpleExcelReader::create(storage_path('app/public/'.$data['file']));

                    $ptba = \App\Models\Ptba::query()->updateOrCreate(
                        ['departement_id' => request()->user()->departement_id],
                        [
                            'file'=> storage_path('app/public/'.$data['file'])
                        ]
                    );

                    Ild::query()->where('ptba_id',$ptba->id)->delete();
                    Rld::query()->where('ptba_id',$ptba->id)->delete();

                    foreach ($excel->getRows()->toArray() as $row) {

                        $ild = Ild::create([
                            'titre'=> $row['Indicateur Lié au Décaissement (ILD)'],
                            'ptba_id'=>$ptba->id,
                        ]);


                        $rld  = Rld::create([
                            'departement_id'=>request()->user()->departement_id,
                            'ptba_id'=>$ptba->id,
                            'titre'=> $row['Résultat Lié au Décaissement (RLD)'],
                            'ild_id'=>$ild->id,
                            'date_debut'=>$row['Date debut'],
                            'date_fin'=>$row['Date fin'],
                            'description'=>$row['Description'],
                            'zone'=>$row['Zone concernée'],
                            'cible'=>$row['Cibles concernées'],
                            'source'=>$row['Source des données'],
                            'methodologie_verification'=>$row['Méthodologie pour la vérification'],
                            'montant'=>$row['montant'],
                            'unite'=>$row['unite'],
                            'categorie'=>$row['categorie'],
                        ]);
                    }

                    Notification::make()->success()->title("PTBA Mofifier")->send();
                }),
            \Filament\Tables\Actions\Action::make('Soumettre')
                ->button()
                ->hidden(fn($record) => $record->status != 10)
                ->action(fn($record) => $record->update(['status'=>'20'])),
            DeleteAction::make('supprimer')->iconButton()
        ];
    }

}
