<?php

namespace App\Filament\Pages\analyse;

use App\Models\AnalyseEquite; // Assuming you have a model for Equity analysis
use Filament\Actions\Action;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Tables\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Spatie\SimpleExcel\SimpleExcelReader;

class analyse_equite extends Page implements HasTable
{
    use InteractsWithTable;

    protected static ?string $title = "Analyses équité";
    protected static ?string $navigationGroup = "Analyses";
    protected static ?string $navigationLabel = "Analyses équité";
    protected static string $view = 'filament.pages.analyse.analyse_equite';

    public function getTableQuery()
    {
        return AnalyseEquite::query(); // Adjust the model as necessary
    }

    public static function getNavigationBadge(): ?string
    {
        return AnalyseEquite::query()->count(); // TODO: Change the autogenerated stub
    }


    protected function getHeaderActions(): array
    {
        return [
            Action::make('Importer')
                ->label('Importer')
                ->action(function($data){
                    $rows = SimpleExcelReader::create(storage_path('app/public/'.$data['file']))->getRows();
                    foreach ($rows->toArray() as $row) {
                        AnalyseEquite::create([
                            'central_issue_id'=>null,
                            'causes_immediate'=>$row['CAUSES IMMEDIATES'],
                            'causes_sjacent'=>$row['CAUSES SOUS-JASCENTES'],
                            'causes_struct'=>$row['CAUSES STRUCTURELLES'],
                            'consequence'=>$row['CONSEQUENCES'],
                        ]);
                    }

                    Notification::make()
                        ->title("Fichier importé")
                        ->success()
                        ->send();
                })
                ->form([
                    FileUpload::make('file')
                ]),
            Action::make('Ajouter')
                ->label('Ajouter')
                ->action(function($data){
                    (new AnalyseEquite())->fill($data)->save();
                    Notification::make()->title("Analyse enregistrée")->success()->send();
                })
                ->form([
                    Select::make('categorie')->options([
                        'VULNERABLES'=>'VULNERABLES','DEFAVORISES'=>'DEFAVORISES','MARGINALISES'=>'MARGINALISES'
                    ]),
                    RichEditor::make('description'),
                    RichEditor::make('cause')->label("Causes de leur situation")
                ])
        ];
    }

    protected function getTableColumns(): array
    {
        return [
            TextColumn::make('id'),
            TextColumn::make('categorie')->label('Categorie'),
            TextColumn::make('created_at')->label('Date'),
        ];
    }

    public function getTableActions(): array
    {
        return [
            \Filament\Tables\Actions\Action::make('Soumettre')
                ->button()
                ->action(function($record){
                    $record->save();
                }),
            \Filament\Tables\Actions\Action::make('Télécharger')
                ->icon('heroicon-o-folder-arrow-down')
                ->iconButton()
                ->action(function($record){
                    $record->save();
                }),

            EditAction::make('Modifier')
                ->iconButton()
                ->form([
                    Select::make('categorie')->options([
                        'VULNERABLES','DEFAVORISES','MARGINALISES'
                    ]),
                    RichEditor::make('description'),
                    RichEditor::make('cause')->label("Causes de leur situation")
                ]),

            \Filament\Tables\Actions\DeleteAction::make('Supprimer')->iconButton(),

        ];
    }
}
