<?php

namespace App\Filament\Pages\analyse;

use App\Models\AnalyseSwot; // Assuming you have a model for SWOT analysis
use Filament\Actions\Action;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Pages\Page;
use Filament\Tables\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;

class analyse_swot extends Page implements HasTable
{
    use InteractsWithTable;

    protected static ?string $title = "Analyses SWOT";
    protected static ?string $navigationGroup = "Analyses";
    protected static ?string $navigationLabel = "Analyses SWOT";
    protected static string $view = 'filament.pages.analyse.analyse_swot';

    public function getTableQuery()
    {
        return AnalyseSwot::query(); // Adjust the model as necessary
    }

    public static function getNavigationBadge(): ?string
    {
        return AnalyseSwot::query()->count(); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('Ajouter')
                ->label('Ajouter')
                ->form([
                    RichEditor::make('swot_content')->label('Contenu SWOT'),
                ])
        ];
    }

    protected function getTableColumns(): array
    {
        return [
            TextColumn::make('id'),
            TextColumn::make('swot_content')->label('Contenu SWOT'),
        ];
    }

    public function getTableActions(): array
    {
        return [
            \Filament\Tables\Actions\Action::make('Soumettre')
                ->button()
                ->action(function($record){
                    $record->save();
                }),
            \Filament\Tables\Actions\Action::make('Télécharger')
                ->icon('heroicon-o-folder-arrow-down')
                ->iconButton()
                ->action(function($record){
                    $record->save();
                }),

            EditAction::make('Modifier')
                ->iconButton()
                ->form([
                    Select::make('categorie')->options([
                        'VULNERABLES','DEFAVORISES','MARGINALISES'
                    ]),
                    RichEditor::make('description'),
                    RichEditor::make('cause')->label("Causes de leur situation")
                ]),

            \Filament\Tables\Actions\DeleteAction::make('Supprimer')->iconButton(),

        ];
    }
}
